---
abstract: 'ExtUtils::MakeMaker based module installer for XS modules.'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Deep: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.96, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Panda-Install
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.1.2
